services:
  postgres:
    image: postgres:latest
    container_name: manageusers-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: user-management
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  backend:
    build: ./user-management-backend
    container_name: manageusers-backend
    command: npm run dev
    ports:
      - 3000:3000
    env_file:
      - ./user-management-backend/.env
    depends_on:
      - postgres

  frontend:
    container_name: manageusers-frontend
    build: ./user-management-frontend
    command: npm run dev
    ports:
      - 8080:8080
    depends_on:
      - backend

volumes:
  postgres-data:
